### ISSUE TITLE
Allow to marshal and unmarshal

### ISSUE THREAD

**Issue by cannon73** [1Password/srp#31]
I have some doubts about the SRP software. There is no way to marshal a SRP structure because all the fields are private. Kindly add these methods.

[marshal.go.txt](https://github.com/1Password/srp/files/5972742/marshal.go.txt)

**Comment by DCKcode** [comment]
Hi @cannon73 - thanks for the suggestion. Could you open a pull request so we can review your additions there?

**Comment by elliotcourant** [comment]
If it's alright, I'd be happy to take this on if a Pull Request would still be welcome? @DCKcode

**Comment by DCKcode** [comment]
Sure - feel free to do that!
